[package]
name = "file_explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "=0.33.2"
egui = "0.33.2"
egui_extras = "0.33.2"
chrono = "=0.4.42"
dirs = "6.0.0"
serde = "1.0.228"
serde_json = "1.0.145"
open = "5.3.3"